#include "../00_Foundation/Base.h"
#include "../102_Spiral3Corpus/Spiral3Corpus.h"
#include "../103_ReuseRepresentationCandidate/ReuseRepresentationCandidate.h"
#include "../104_ReuseRepresentationPlanner/ReuseRepresentationPlanner.h"
#include "../105_ReuseRepresentationVerifier/ReuseRepresentationVerifier.h"
#include <array>
#include <filesystem>
#include <iostream>
namespace b=sge4_5::base;namespace c=sge4_5::spiral3::corpus;namespace k=sge4_5::spiral3::candidate;namespace p=sge4_5::spiral3::planner;namespace v=sge4_5::spiral3::verification;
int main(int argc,char**argv){auto h=c::BuildCanonicalMeasurementHierarchyV1();if(!h)return 1;auto cases=c::BuildReuseCorpusV1(h.Value());if(!cases)return 2;const std::array kinds{k::CandidateKindV1::MatrixHierarchy,k::CandidateKindV1::DirectPgaHierarchy,k::CandidateKindV1::HybridHierarchy};b::BinaryWriter writer;std::uint32_t verifiedCount=0;for(const auto& rc:cases.Value())for(const auto kind:kinds){auto raw=p::PlanCandidateGraphV1(h.Value(),rc.semantic,kind);if(!raw)return 3;auto verified=v::VerifyCandidateGraphV1(h.Value(),rc.semantic,raw.Value());if(!verified)return 4;const auto expectedNodes=kind==k::CandidateKindV1::DirectPgaHierarchy?4u:5u;const auto expectedEdges=kind==k::CandidateKindV1::DirectPgaHierarchy?3u:4u;if(raw.Value().nodes.size()!=expectedNodes||raw.Value().edges.size()!=expectedEdges||raw.Value().commonSourceDispatchCount!=2||verified.Value().Plan().reuseCount!=rc.reuseCount||verified.Value().Plan().pointCount!=rc.semantic.pointCount)return 5;auto rawBytes=k::SerializeRawCandidateGraphV1(raw.Value()),verifiedBytes=v::SerializeVerifiedReuseRepresentationV1(verified.Value());writer.WriteU32(static_cast<std::uint32_t>(rawBytes.size()));writer.WriteBytes(rawBytes);writer.WriteU32(static_cast<std::uint32_t>(verifiedBytes.size()));writer.WriteBytes(verifiedBytes);++verifiedCount;}auto evidence=std::move(writer).Take();if(argc==3&&std::string(argv[1])=="--emit"){auto result=b::WriteAllBytes(std::filesystem::path(argv[2]),evidence);if(!result)return 6;}std::cout<<"Spiral 3 verified candidate graphs passed: "<<verifiedCount<<" reuse/candidate plans. SHA-256: "<<b::ToHex(b::Sha256(evidence))<<'\n';return verifiedCount==18?0:7;}
