#include "ReuseRepresentationCandidate.h"
#include "../81_Spiral2Contracts/Spiral2Contracts.h"
#include <span>
#include <string_view>
namespace sge4_5::spiral3::candidate
{
namespace{base::Digest256 Lit(std::string_view v){return base::Sha256(std::as_bytes(std::span(v.data(),v.size())));}constexpr std::uint32_t Groups(std::uint32_t c){return(c+63u)/64u;}}
base::Digest256 ProgramIdentityV1(OperationKindV1 op){switch(op){case OperationKindV1::DynamicInvocationSource:return Lit("S3.L0.DynamicInvocationSource.V1");case OperationKindV1::ConsumerPointSource:return Lit("S3.L1.ConsumerPointSource.V1");case OperationKindV1::LocalMotorToMatrix:return Lit("S3.A0.LocalMotorToMatrix.V1");case OperationKindV1::MatrixHierarchy:return Lit("S3.A1.MatrixHierarchy.SerialCanonicalOrder.V1");case OperationKindV1::MatrixConsumerApply:return Lit("S3.MatrixConsumerApply.V1");case OperationKindV1::MotorHierarchy:return Lit("S3.MotorHierarchy.SerialCanonicalOrder.V1");case OperationKindV1::DirectPgaConsumerApply:return Lit("S3.B1.DirectPgaConsumerApply.V1");case OperationKindV1::GlobalMotorToMatrix:return Lit("S3.C1.GlobalMotorToMatrix.V1");default:return {};}}
std::vector<std::byte> SerializeCandidateNodeV1(const CandidateNodeV1&n){base::BinaryWriter w;w.WriteU32(n.ordinal);w.WriteU32(static_cast<std::uint32_t>(n.operation));w.WriteU32(n.primaryInputStride);w.WriteU32(n.primaryInputElementCount);w.WriteU32(n.primaryOutputStride);w.WriteU32(n.primaryOutputElementCount);w.WriteU32(n.secondaryInputStride);w.WriteU32(n.secondaryInputElementCount);w.WriteU32(n.secondaryOutputStride);w.WriteU32(n.secondaryOutputElementCount);w.WriteU32(n.dispatchX);w.WriteU32(n.dispatchY);w.WriteU32(n.dispatchZ);w.WriteU32(0);w.WriteBytes(n.programIdentity);return std::move(w).Take();}
base::Digest256 CandidateNodeIdentityV1(const CandidateNodeV1&n){return base::Sha256(SerializeCandidateNodeV1(n));}
base::Result<RawCandidateGraphV1,std::string> BuildRawCandidateGraphV1(const spiral2::hierarchy::RigidHierarchySemanticV1& h,const semantic::ReuseSweepSemanticV1& s,CandidateKindV1 kind)
{
    auto valid=semantic::ValidateReuseSweepSemanticV1(h,s);if(!valid)return base::Result<RawCandidateGraphV1,std::string>::Failure(valid.Error());RawCandidateGraphV1 g;g.reuseSemanticIdentity=semantic::ReuseSweepSemanticIdentityV1(s);g.hierarchySemanticIdentity=s.hierarchySemanticIdentity;g.dynamicInvocationSchemaIdentity=spiral2::contracts::DynamicPaletteInvocationSchemaIdentityV1(spiral2::contracts::BuildDynamicPaletteInvocationSchemaV1(h));g.localPointCorpusIdentity=s.localPointCorpusIdentity;g.observationContractIdentity=s.observationContractIdentity;g.kind=kind;g.boneCount=s.boneCount;g.reuseCount=s.reuseCount;g.pointCount=s.pointCount;g.proposedHierarchyExecutionModel=HierarchyExecutionModelV1::SingleDispatchCanonicalOrderSerial;g.hierarchyDepthCount=static_cast<std::uint32_t>(h.depthOffsets.size()-1);g.commonSourceDispatchCount=2;
    auto add=[&](OperationKindV1 op,std::uint32_t inStride,std::uint32_t inCount,std::uint32_t outStride,std::uint32_t outCount,std::uint32_t dispatch,std::uint32_t secondStride=0,std::uint32_t secondCount=0){CandidateNodeV1 n;n.ordinal=static_cast<std::uint32_t>(g.nodes.size());n.operation=op;n.primaryInputStride=inStride;n.primaryInputElementCount=inCount;n.primaryOutputStride=outStride;n.primaryOutputElementCount=outCount;n.secondaryInputStride=secondStride;n.secondaryInputElementCount=secondCount;n.secondaryOutputStride=secondStride;n.secondaryOutputElementCount=secondCount;n.dispatchX=dispatch;n.programIdentity=ProgramIdentityV1(op);g.nodes.push_back(n);return n.ordinal;};
    const auto dynamic=add(OperationKindV1::DynamicInvocationSource,32,s.boneCount,32,s.boneCount,Groups(s.pointCount),16,s.pointCount);
    const auto points=add(OperationKindV1::ConsumerPointSource,0,0,16,s.pointCount,Groups(s.pointCount));
    auto edge=[&](std::uint32_t a,std::uint32_t b){g.edges.push_back({a,b});};
    switch(kind){case CandidateKindV1::MatrixHierarchy:{const auto a=add(OperationKindV1::LocalMotorToMatrix,32,s.boneCount,48,s.boneCount,Groups(s.boneCount));const auto b=add(OperationKindV1::MatrixHierarchy,48,s.boneCount,48,s.boneCount,1);const auto c=add(OperationKindV1::MatrixConsumerApply,48,s.boneCount,16,s.pointCount,Groups(s.pointCount),16,s.pointCount);edge(dynamic,a);edge(a,b);edge(b,c);edge(points,c);g.proposedLoweringPosition=MatrixLoweringPositionV1::BeforeHierarchy;break;}case CandidateKindV1::DirectPgaHierarchy:{const auto a=add(OperationKindV1::MotorHierarchy,32,s.boneCount,32,s.boneCount,1);const auto b=add(OperationKindV1::DirectPgaConsumerApply,32,s.boneCount,16,s.pointCount,Groups(s.pointCount),16,s.pointCount);edge(dynamic,a);edge(a,b);edge(points,b);g.proposedLoweringPosition=MatrixLoweringPositionV1::Absent;break;}case CandidateKindV1::HybridHierarchy:{const auto a=add(OperationKindV1::MotorHierarchy,32,s.boneCount,32,s.boneCount,1);const auto b=add(OperationKindV1::GlobalMotorToMatrix,32,s.boneCount,48,s.boneCount,Groups(s.boneCount));const auto c=add(OperationKindV1::MatrixConsumerApply,48,s.boneCount,16,s.pointCount,Groups(s.pointCount),16,s.pointCount);edge(dynamic,a);edge(a,b);edge(b,c);edge(points,c);g.proposedLoweringPosition=MatrixLoweringPositionV1::AfterHierarchy;break;}default:return base::Result<RawCandidateGraphV1,std::string>::Failure("unknown candidate kind");}
    g.proposedCandidateLeafDispatchCount=static_cast<std::uint32_t>(g.nodes.size())-g.commonSourceDispatchCount;return base::Result<RawCandidateGraphV1,std::string>::Success(std::move(g));
}
std::vector<std::byte> SerializeRawCandidateGraphV1(const RawCandidateGraphV1&g){base::BinaryWriter w;w.WriteBytes(Lit("SGE4-5.Spiral3.RawCandidateGraph.V1"));w.WriteBytes(g.reuseSemanticIdentity);w.WriteBytes(g.hierarchySemanticIdentity);w.WriteBytes(g.dynamicInvocationSchemaIdentity);w.WriteBytes(g.localPointCorpusIdentity);w.WriteBytes(g.observationContractIdentity);w.WriteU32(static_cast<std::uint32_t>(g.kind));w.WriteU32(g.boneCount);w.WriteU32(g.reuseCount);w.WriteU32(g.pointCount);w.WriteU32(static_cast<std::uint32_t>(g.nodes.size()));w.WriteU32(static_cast<std::uint32_t>(g.edges.size()));w.WriteU32(static_cast<std::uint32_t>(g.proposedLoweringPosition));w.WriteU32(static_cast<std::uint32_t>(g.proposedHierarchyExecutionModel));w.WriteU32(g.hierarchyDepthCount);w.WriteU32(g.commonSourceDispatchCount);w.WriteU32(g.proposedCandidateLeafDispatchCount);for(const auto&n:g.nodes){const auto bytes=SerializeCandidateNodeV1(n);w.WriteU32(static_cast<std::uint32_t>(bytes.size()));w.WriteBytes(bytes);}for(const auto&e:g.edges){w.WriteU32(e.source);w.WriteU32(e.destination);}return std::move(w).Take();}
base::Digest256 RawCandidateGraphIdentityV1(const RawCandidateGraphV1&g){return base::Sha256(SerializeRawCandidateGraphV1(g));}
}
