$ErrorActionPreference='Stop';$testsRoot=Split-Path -Parent $MyInvocation.MyCommand.Path;$root=Split-Path -Parent $testsRoot;. (Join-Path $testsRoot 'tools\Sha256.ps1')
function Invoke-Checked([string]$f,[string[]]$a=@()){&$f @a;if($LASTEXITCODE-ne 0){throw "Command failed: $f"}}
function MSBuild{$v=Join-Path ${env:ProgramFiles(x86)} 'Microsoft Visual Studio\Installer\vswhere.exe';$m=&$v -latest -products * -requires Microsoft.Component.MSBuild -find 'MSBuild\**\Bin\MSBuild.exe'|Select-Object -Last 1;if(-not$m){throw 'MSBuild missing'};$m}
function Equal([string]$a,[string]$b){$x=[IO.File]::ReadAllBytes($a);$y=[IO.File]::ReadAllBytes($b);if($x.Length-ne$y.Length){return $false};for($i=0;$i-lt$x.Length;++$i){if($x[$i]-ne$y[$i]){return $false}};$true}
foreach($script in @('tools\Verify-SGE4_5Identity.ps1','tools\Verify-Spiral2ResearchContract.ps1','tools\Verify-Spiral2CU2.ps1','tools\Verify-SourceManifest.ps1')){Invoke-Checked powershell.exe @('-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',(Join-Path $testsRoot $script))};Invoke-Checked powershell.exe @('-NoLogo','-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',(Join-Path $root 'verify_dependencies.ps1'))
$m=MSBuild;foreach($c in @('Debug','Release')){Invoke-Checked $m @((Join-Path $root 'SemanticGpuEngine4-5.sln'),'/m','/nologo','/t:Build',"/p:Configuration=$c",'/p:Platform=x64','/v:minimal')}
$d92=Join-Path $root 'build\bin\x64\Debug\92_Spiral2CandidateGraphTests.exe';$r92=Join-Path $root 'build\bin\x64\Release\92_Spiral2CandidateGraphTests.exe';$d93=Join-Path $root 'build\bin\x64\Debug\93_Spiral2AuthorityMutationTests.exe';$r93=Join-Path $root 'build\bin\x64\Release\93_Spiral2AuthorityMutationTests.exe';foreach($e in @($d92,$r92,$d93,$r93)){Invoke-Checked $e}
$o=Join-Path $root 'build\tests\spiral2-cu2';New-Item -ItemType Directory -Force -Path $o|Out-Null;$a=Join-Path $o 'debug-a.bin';$b=Join-Path $o 'debug-b.bin';$r=Join-Path $o 'release.bin';Invoke-Checked $d92 @('--emit',$a);Invoke-Checked $d92 @('--emit',$b);Invoke-Checked $r92 @('--emit',$r);if(-not(Equal $a $b)-or-not(Equal $a $r)){throw 'Verified graph artifacts are not deterministic.'}
Write-Host '============================================================';Write-Host 'SGE4-5 SPIRAL 2 COMPLETION UNIT 2 PASSED';Write-Host 'Three candidate graphs, independent verification, and mutation authority';Write-Host "Verified graph SHA-256: $(Get-SGE4FileSha256 $a)";Write-Host '============================================================'
